/*
File: play_audio.js
Author: Eni Mustafaraj
Date: 03/23/2014
Purpose: The Javascript code for the file "play_audio.html". When 
a user clicks one of the "sound icons", this code 
sets the attributes for the <audio> element that will play the 
sound (in our case the audio file is the pronounciation of a 
vocabulary word.

This app uses the Google dictionary Web API to get pronounciation
audio files for the words.

WEB RESOURCES consulted for this app
How to get MP3 audio pronunciation file of any dictionary word
http://www.techvigil.com/tips-tricks/347/mp3-pronunciation-files/

Total number of code lines: 14.
*/

/* Event handler function for the sound icon click event. The function
uses the special variable this to access the icon that was clicked, then gets its siblings (the 
span element from which it can get the word to be pronounced and the 
audio element, to which it will attach the right attributes to perform
the playing event.
*/

function playSound(){

    console.log("this is "+this);
    gthis = this;

    //get the text from the <span> element that is its previous sibling
    //Check the HTML code to see that <img> and <span> are siblings.
    var word = this.previousSibling.innerHTML;

    console.log("word is: "+word);    // here's the interesting stuff
	
    // get the <audio> element which is its next sibling
    var audio = this.nextSibling;
	
    // specify values for the attributes of the <audio> element
    // notice how the URL is generated by concatenating a fixed part 
    // with the concrete word
    var src = "https://ssl.gstatic.com/dictionary/static/sounds/de/0/" 
            + word + ".mp3";							
    audio.setAttribute("src", src);
}

// get the list of img elements that are sound icons
var iconsList = document.querySelectorAll("#words img");
// iterate through the list to bind to every element the event handler
// for the onclick event
for (var i=0; i < iconsList.length; i++){
    var icon = iconsList[i];
    icon.onclick = playSound;
}
